window.RECRUITMENT_DATA = {
  "source": "Historical Recruitmet Records 2026.xlsx",
  "sheet": "Recruitment",
  "sourceRange": "A3:O35",
  "prepared": "2026-09-17",
  "latestActivity": "2026-08-25",
  "records": [
    {
      "record": 1,
      "sourceRow": 3,
      "jobId": "1710729",
      "title": "Center Director - BCBA",
      "family": "Center Director",
      "city": "Pikesville",
      "state": "Maryland",
      "posted": "2026-02-04",
      "sponsoredDate": null,
      "sponsored": "Yes",
      "amount": null,
      "status": "Completed",
      "outcome": "2026-04-14",
      "days": 69,
      "eligible": true,
      "conflict": false,
      "flags": [
        "Sponsorship amount missing."
      ]
    },
    {
      "record": 2,
      "sourceRow": 4,
      "jobId": "1742365",
      "title": "Center Director",
      "family": "Center Director",
      "city": "Pikesville",
      "state": "Maryland",
      "posted": "2026-03-19",
      "sponsoredDate": null,
      "sponsored": "Yes",
      "amount": null,
      "status": "Completed",
      "outcome": "2026-04-14",
      "days": 26,
      "eligible": true,
      "conflict": false,
      "flags": [
        "Sponsorship amount missing."
      ]
    },
    {
      "record": 3,
      "sourceRow": 5,
      "jobId": "1742389",
      "title": "Case Manager - Admin",
      "family": "Case Manager",
      "city": "Pikesville",
      "state": "Maryland",
      "posted": "2026-03-19",
      "sponsoredDate": null,
      "sponsored": "Yes",
      "amount": null,
      "status": "Completed",
      "outcome": "2026-04-14",
      "days": 26,
      "eligible": true,
      "conflict": false,
      "flags": [
        "Sponsorship amount missing."
      ]
    },
    {
      "record": 4,
      "sourceRow": 6,
      "jobId": "1740559",
      "title": "Recruiter - BCBA",
      "family": "Recruiter - BCBA",
      "city": "Hollywood",
      "state": "Florida",
      "posted": "2026-03-17",
      "sponsoredDate": "2026-04-22",
      "sponsored": "Yes",
      "amount": 249.0,
      "status": "Completed",
      "outcome": "2026-04-24",
      "days": 38,
      "eligible": false,
      "conflict": true,
      "flags": [
        "Completed status; note says posting removed. Excluded from time to fill."
      ]
    },
    {
      "record": 5,
      "sourceRow": 7,
      "jobId": "1694443",
      "title": "Case Manager",
      "family": "Case Manager",
      "city": "Santa Ana",
      "state": "California",
      "posted": "2026-01-13",
      "sponsoredDate": "2026-02-03",
      "sponsored": "Yes",
      "amount": 250.0,
      "status": "Removed",
      "outcome": "2026-04-28",
      "days": 105,
      "eligible": false,
      "conflict": false,
      "flags": []
    },
    {
      "record": 6,
      "sourceRow": 8,
      "jobId": "1769005",
      "title": "Intake Coordinator",
      "family": "Intake Coordinator",
      "city": "Glendale",
      "state": "Arizona",
      "posted": "2026-04-16",
      "sponsoredDate": "2026-04-16",
      "sponsored": "Yes",
      "amount": null,
      "status": "Completed",
      "outcome": "2026-05-05",
      "days": 19,
      "eligible": true,
      "conflict": false,
      "flags": [
        "Sponsorship amount missing."
      ]
    },
    {
      "record": 7,
      "sourceRow": 9,
      "jobId": "1835245",
      "title": "Intake Coordinator",
      "family": "Intake Coordinator",
      "city": "Hollywood",
      "state": "Florida",
      "posted": "2026-04-17",
      "sponsoredDate": "2026-04-17",
      "sponsored": "Yes",
      "amount": null,
      "status": "Completed",
      "outcome": "2026-05-05",
      "days": 18,
      "eligible": true,
      "conflict": false,
      "flags": [
        "Sponsorship amount missing."
      ]
    },
    {
      "record": 8,
      "sourceRow": 10,
      "jobId": "1742500",
      "title": "Case Manager - Admin",
      "family": "Case Manager",
      "city": "American Fork",
      "state": "Utah",
      "posted": "2026-03-19",
      "sponsoredDate": "2026-04-14",
      "sponsored": "Yes",
      "amount": null,
      "status": "Removed",
      "outcome": "2026-05-13",
      "days": 55,
      "eligible": false,
      "conflict": false,
      "flags": [
        "Sponsorship amount missing."
      ]
    },
    {
      "record": 9,
      "sourceRow": 11,
      "jobId": "1694457",
      "title": "Center Director",
      "family": "Center Director",
      "city": "Santa Ana",
      "state": "California",
      "posted": "2026-01-13",
      "sponsoredDate": "2026-04-14",
      "sponsored": "Yes",
      "amount": 250.0,
      "status": "Removed",
      "outcome": "2026-05-14",
      "days": 121,
      "eligible": false,
      "conflict": false,
      "flags": []
    },
    {
      "record": 10,
      "sourceRow": 12,
      "jobId": "1730295",
      "title": "Clinical Center Director",
      "family": "Center Director",
      "city": "Irvine",
      "state": "California",
      "posted": "2026-03-02",
      "sponsoredDate": null,
      "sponsored": "No",
      "amount": null,
      "status": "Removed",
      "outcome": "2026-05-14",
      "days": 73,
      "eligible": false,
      "conflict": false,
      "flags": []
    },
    {
      "record": 11,
      "sourceRow": 13,
      "jobId": "1857328",
      "title": "Case Manager - Admin",
      "family": "Case Manager",
      "city": "Stone Mountain",
      "state": "Georgia",
      "posted": "2026-05-13",
      "sponsoredDate": "2026-05-14",
      "sponsored": "Yes",
      "amount": 250.0,
      "status": "On Hold",
      "outcome": "2026-05-27",
      "days": 14,
      "eligible": false,
      "conflict": false,
      "flags": []
    },
    {
      "record": 12,
      "sourceRow": 14,
      "jobId": "1749919",
      "title": "Intake Coordinator (ABA)",
      "family": "Intake Coordinator",
      "city": "Honolulu",
      "state": "Hawaii",
      "posted": "2026-03-31",
      "sponsoredDate": "2026-04-06",
      "sponsored": "Yes",
      "amount": 250.0,
      "status": "Completed",
      "outcome": "2026-05-27",
      "days": 57,
      "eligible": true,
      "conflict": false,
      "flags": []
    },
    {
      "record": 13,
      "sourceRow": 15,
      "jobId": "1427197",
      "title": "Outreach Coordinator",
      "family": "Outreach Coordinator",
      "city": "Hollywood",
      "state": "Florida",
      "posted": "2026-04-27",
      "sponsoredDate": null,
      "sponsored": "No",
      "amount": null,
      "status": "Completed",
      "outcome": "2026-05-29",
      "days": 32,
      "eligible": true,
      "conflict": false,
      "flags": []
    },
    {
      "record": 14,
      "sourceRow": 16,
      "jobId": "1868672",
      "title": "Clinical Talent Acquistion Manager",
      "family": "Clinical Talent Acquisition Manager",
      "city": "Hollywood",
      "state": "Florida",
      "posted": "2026-05-29",
      "sponsoredDate": null,
      "sponsored": "Unknown",
      "amount": null,
      "status": "Completed",
      "outcome": "2026-06-06",
      "days": 8,
      "eligible": true,
      "conflict": false,
      "flags": []
    },
    {
      "record": 15,
      "sourceRow": 17,
      "jobId": "1844688",
      "title": "Account Executive",
      "family": "Account Executive",
      "city": "Hollywood",
      "state": "Florida",
      "posted": "2026-05-13",
      "sponsoredDate": "2026-05-13",
      "sponsored": "Yes",
      "amount": 150.0,
      "status": "Completed",
      "outcome": "2026-06-08",
      "days": 26,
      "eligible": true,
      "conflict": false,
      "flags": []
    },
    {
      "record": 16,
      "sourceRow": 18,
      "jobId": "1865757",
      "title": "HR Coordinator",
      "family": "HR Coordinator",
      "city": "Hollywood",
      "state": "Florida",
      "posted": "2026-05-25",
      "sponsoredDate": "2026-06-05",
      "sponsored": "Yes",
      "amount": 200.0,
      "status": "Removed",
      "outcome": "2026-06-12",
      "days": 18,
      "eligible": false,
      "conflict": false,
      "flags": []
    },
    {
      "record": 17,
      "sourceRow": 19,
      "jobId": "1868201",
      "title": "HR Coordinator",
      "family": "HR Coordinator",
      "city": "Honolulu",
      "state": "Hawaii",
      "posted": "2026-05-26",
      "sponsoredDate": "2026-06-05",
      "sponsored": "Yes",
      "amount": 200.0,
      "status": "Completed",
      "outcome": "2026-06-10",
      "days": 15,
      "eligible": true,
      "conflict": false,
      "flags": []
    },
    {
      "record": 18,
      "sourceRow": 20,
      "jobId": "1616135",
      "title": "Senior Front-End Developer",
      "family": "Senior Front-End Developer",
      "city": "Hollywood",
      "state": "Florida",
      "posted": "2026-05-05",
      "sponsoredDate": null,
      "sponsored": "Unknown",
      "amount": null,
      "status": "On Hold",
      "outcome": "2026-06-16",
      "days": 42,
      "eligible": false,
      "conflict": false,
      "flags": []
    },
    {
      "record": 19,
      "sourceRow": 21,
      "jobId": "1835245",
      "title": "Intake Coordinator",
      "family": "Intake Coordinator",
      "city": "Hollywood",
      "state": "Florida",
      "posted": "2026-05-12",
      "sponsoredDate": null,
      "sponsored": "Unknown",
      "amount": null,
      "status": "Completed",
      "outcome": "2026-06-18",
      "days": 37,
      "eligible": true,
      "conflict": false,
      "flags": []
    },
    {
      "record": 20,
      "sourceRow": 22,
      "jobId": "1857264",
      "title": "Center Director – ABA",
      "family": "Center Director",
      "city": "Pikesville",
      "state": "Maryland",
      "posted": "2026-05-12",
      "sponsoredDate": "2026-06-03",
      "sponsored": "Yes",
      "amount": 564.0,
      "status": "Completed",
      "outcome": "2026-06-22",
      "days": 41,
      "eligible": true,
      "conflict": false,
      "flags": []
    },
    {
      "record": 21,
      "sourceRow": 23,
      "jobId": "1880457",
      "title": "Case Manager",
      "family": "Case Manager",
      "city": "Hollywood",
      "state": "Florida",
      "posted": "2026-06-16",
      "sponsoredDate": "2026-07-02",
      "sponsored": "Yes",
      "amount": 500.0,
      "status": "Removed",
      "outcome": "2026-07-07",
      "days": 21,
      "eligible": false,
      "conflict": false,
      "flags": []
    },
    {
      "record": 22,
      "sourceRow": 24,
      "jobId": "1872423",
      "title": "Recruiter & Talent Acquisition Specialist - BCBA",
      "family": "Recruiter & Talent Acquisition Specialist - BCBA",
      "city": "Glendale",
      "state": "Arizona",
      "posted": "2026-06-03",
      "sponsoredDate": null,
      "sponsored": "No",
      "amount": null,
      "status": "Removed",
      "outcome": "2026-07-08",
      "days": 35,
      "eligible": false,
      "conflict": false,
      "flags": []
    },
    {
      "record": 23,
      "sourceRow": 25,
      "jobId": "1872405",
      "title": "Recruiter & Talent Acquisition Specialist - BCBA",
      "family": "Recruiter & Talent Acquisition Specialist - BCBA",
      "city": "Not specified",
      "state": "California",
      "posted": "2026-06-03",
      "sponsoredDate": null,
      "sponsored": "No",
      "amount": null,
      "status": "Removed",
      "outcome": "2026-07-08",
      "days": 35,
      "eligible": false,
      "conflict": false,
      "flags": [
        "City field contains the state name; city not specified."
      ]
    },
    {
      "record": 24,
      "sourceRow": 26,
      "jobId": "1890242",
      "title": "Outreach Coordinator",
      "family": "Outreach Coordinator",
      "city": "Lawrenceville",
      "state": "Georgia",
      "posted": "2026-06-30",
      "sponsoredDate": "2026-07-02",
      "sponsored": "Yes",
      "amount": 300.0,
      "status": "Completed",
      "outcome": "2026-07-16",
      "days": 16,
      "eligible": true,
      "conflict": false,
      "flags": []
    },
    {
      "record": 25,
      "sourceRow": 27,
      "jobId": "1871998",
      "title": "Center Director",
      "family": "Center Director",
      "city": "Norcross",
      "state": "Georgia",
      "posted": "2026-06-02",
      "sponsoredDate": null,
      "sponsored": "Unknown",
      "amount": null,
      "status": "Completed",
      "outcome": "2026-07-16",
      "days": 44,
      "eligible": true,
      "conflict": false,
      "flags": []
    },
    {
      "record": 26,
      "sourceRow": 28,
      "jobId": "1857100",
      "title": "RBT",
      "family": "RBT",
      "city": "Stone Mountain",
      "state": "Georgia",
      "posted": "2026-05-12",
      "sponsoredDate": null,
      "sponsored": "Unknown",
      "amount": null,
      "status": "Completed",
      "outcome": "2026-07-16",
      "days": 65,
      "eligible": true,
      "conflict": false,
      "flags": []
    },
    {
      "record": 27,
      "sourceRow": 29,
      "jobId": "1879024",
      "title": "Recruiting Coordinator",
      "family": "Recruiting Coordinator",
      "city": "Hollywood",
      "state": "Florida",
      "posted": "2026-06-12",
      "sponsoredDate": null,
      "sponsored": "Unknown",
      "amount": null,
      "status": "Removed",
      "outcome": null,
      "days": null,
      "eligible": false,
      "conflict": false,
      "flags": [
        "Outcome date missing."
      ]
    },
    {
      "record": 28,
      "sourceRow": 30,
      "jobId": "1879030",
      "title": "Talent Acquisition Coordinator",
      "family": "Talent Acquisition Coordinator",
      "city": "Hollywood",
      "state": "Florida",
      "posted": "2026-06-12",
      "sponsoredDate": null,
      "sponsored": "Unknown",
      "amount": null,
      "status": "Removed",
      "outcome": null,
      "days": null,
      "eligible": false,
      "conflict": false,
      "flags": [
        "Outcome date missing."
      ]
    },
    {
      "record": 29,
      "sourceRow": 31,
      "jobId": "1898063",
      "title": "Lead RBT",
      "family": "Lead RBT",
      "city": "Glendale",
      "state": "Arizona",
      "posted": "2026-07-10",
      "sponsoredDate": "2026-07-21",
      "sponsored": "Yes",
      "amount": 300.0,
      "status": "Completed",
      "outcome": "2026-07-31",
      "days": 21,
      "eligible": true,
      "conflict": false,
      "flags": []
    },
    {
      "record": 30,
      "sourceRow": 32,
      "jobId": "1890265",
      "title": "Outreach Advisor",
      "family": "Outreach Advisor",
      "city": "Hollywood",
      "state": "Florida",
      "posted": "2026-06-30",
      "sponsoredDate": "2026-07-02",
      "sponsored": "Yes",
      "amount": 300.0,
      "status": "Removed",
      "outcome": "2026-08-25",
      "days": 56,
      "eligible": false,
      "conflict": false,
      "flags": []
    },
    {
      "record": 31,
      "sourceRow": 33,
      "jobId": "1726166",
      "title": "Registered Behavior Technician",
      "family": "RBT",
      "city": "Silver Spring",
      "state": "Maryland",
      "posted": "2026-02-25",
      "sponsoredDate": "2026-06-03",
      "sponsored": "Yes",
      "amount": 200.0,
      "status": "Completed",
      "outcome": "2026-08-24",
      "days": 180,
      "eligible": true,
      "conflict": false,
      "flags": []
    },
    {
      "record": 32,
      "sourceRow": 34,
      "jobId": "1742469",
      "title": "Center Director",
      "family": "Center Director",
      "city": "American Fork",
      "state": "Utah",
      "posted": "2026-03-19",
      "sponsoredDate": "2026-07-29",
      "sponsored": "Yes",
      "amount": 1009.0,
      "status": "Completed",
      "outcome": "2026-06-24",
      "days": 97,
      "eligible": true,
      "conflict": false,
      "flags": [
        "Sponsorship date is after completion; check source dates."
      ]
    },
    {
      "record": 33,
      "sourceRow": 35,
      "jobId": "1742490",
      "title": "BCBA Center Director",
      "family": "Center Director",
      "city": "American Fork",
      "state": "Utah",
      "posted": "2026-03-19",
      "sponsoredDate": "2026-07-29",
      "sponsored": "Yes",
      "amount": 450.0,
      "status": "Completed",
      "outcome": "2026-06-24",
      "days": 97,
      "eligible": true,
      "conflict": false,
      "flags": [
        "Sponsorship date is after completion; check source dates."
      ]
    }
  ]
};
